version: 3.6.2
url: "https://mirrors.aliyun.com/apache/zookeeper/zookeeper-{{version}}/apache-zookeeper-{{version}}.tar.gz"
app_dir: "/usr/local/apache-zookeeper-{{ version }}"
data_dir: "{{ app_dir }}/data"
log_dir: "{{ app_dir }}/logs"
zk_connect_port: 2888
zk_election_port: 3888
zk_port: 2181
