#注意run_once、delegate_to的使用技巧
- name: 创建 /cephfs/{{ ns }} 目录 
  file:
    name: /cephfs/{{ ns }}
    state: directory
  run_once: true
  delegate_to: 192.168.13.201

- name: 创建 deployment/{{ns}}/prd/init目录
  file:
    name: deployment/{{ns}}/prd/init
    state: directory
  run_once: true
  delegate_to: 192.168.11.20

# key来自于IT提供，且经过base64编码
- name: 添加初始化脚本
  blockinfile:
    path: /root/deployment/{{ns}}/prd/init/init.yml
    block: |-
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: cephfs-{{ns}}-secret
        namespace: {{ns}}
      data:
        key: QVFEQ2xqdGZWT2NnRkJBQVI4ZTRNbEY0dGI1QXUrdHJaOCtHbXc9PQo=
      ---
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: {{ns}}-pv
      spec:
        capacity:
          storage: {{size}}
        accessModes:
          - ReadWriteMany
        cephfs:
          monitors:
            - 10.11.1.1:6789
            - 10.11.1.2:6789
            - 10.11.1.3:6789
          path: /prd/{{ns}}
          user: prd
          secretRef:
            name: cephfs-{{ns}}-secret
          readOnly: false
        persistentVolumeReclaimPolicy: Retain
      ---
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: mypvc
        namespace: {{ns}}
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: {{size}}
        volumeName: {{ns}}-pv
    state: present
    create: yes
    backup: no
    marker: "# Ansible inventory yml {mark}"
  run_once: true
  delegate_to: 192.168.11.20
