- name: 添加docker-aliyun的yum仓库
  yum_repository:
    file: docker-ce #文件名，默认和name一样
    name: docker-ce-stable
    description: Aliyun Docker CE Stable - $basearch
    baseurl: https://mirrors.aliyun.com/docker-ce/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://mirrors.aliyun.com/docker-ce/linux/centos/gpg
    state: present
