- name: create mongodb group
  group:
    name: mongod
    state: present

- name: create mongodb user
  user:
    name: mongod
    group: mongod
    state: present

- name: 创建data目录
  file:
    path: "{{ data_dir}}"
    state: directory
    owner: mongod
    group: mongod

- name: 传递repo文件
  copy: 
    src: mongodb-4.repo
    dest: /etc/yum.repos.d/Mongodb-4.repo
    mode: 0744
  tags:
    - repofile

- name: 传递keyfile文件
  copy: 
    src: secret
    dest: "{{ secret_file }}"
    owner: mongod
    group: mongod
    mode: 0600
  tags:
    - keyfile

- name: 安装一些必要的包 for yum
  yum:
    name: mongodb-org-{{ version }}
    state: present
  tags:
    - yum

- name: disable auto update for mongodb
  lineinfile:
    path: /etc/yum.conf
    line: 'exclude=mongodb-org,mongodb-org-server,mongodb-org-shell,mongodb-org-mongos,mongodb-org-tools'

- name: install necessary tools
  tags:
    - yum
  yum:
    name: bash-completion,unzip,conntrack,ntpdate,ntp,curl,sysstat,libseccomp,wget,vim,net-tools,git,nfs-utils,rpcbind,nload,htop,tree,telnet,python-devel,python-pip,numactl

- name: Install PyMongo from PIP
  pip:
    name: pymongo
    version: 3.7.1

- name: 相关服务管理
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: 'mongod', state: 'stopped', enabled: 'false' }
    - { name: 'firewalld', state: 'stopped', enabled: 'false' }
    - { name: 'postfix', state: 'stopped', enabled: 'false' }

- name: 构建service
  template:
    src: mongodb.service.j2
    dest: "/lib/systemd/system/mongod.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
