- name: 注册replicaset_host变量
  set_fact:
    replicaset_host: []

- name: 循环处理host
  set_fact:
    replicaset_host: "{{replicaset_host}} + [ '{{ item }}:{{ PORT }}' ]"
  with_items: "{{ groups[group] }}"

- name: 提供相关文件
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'repl_set_init.j2', dest: '/tmp/repl_set_init.js' }
  tags:
    - copy_repl_set_init


- name: 初始化副本集,只在第一台执行
  shell: cat /tmp/repl_set_init.js | /usr/bin/mongo localhost:{{ PORT }}/admin -u "{{ root_user_name }}" -p "{{ root_user_passwd }}"
  tags:
    - repl_set_init
