- hosts: "{{ group }}"
  gather_facts: no
  roles:
  #- role: iptables
  - role: iptables_db
  vars:
    state: present
#delete : ansible-playbook iptables.yml -e group=local 
#delete : ansible-playbook iptables.yml -e state=absent -e group=ssh
