- hosts: localhost
  gather_facts: no
  vars: 
    - lists: 
        quzl: 1
        dev: 2
    - env: "{{env}}"
  tasks: 
    - name: loop
      debug: msg="{{lists[env]}}"
      #with_items: '{{lists["{{env}}"]}}'
