- name: 添加k8s-aliyun的yum 仓库
  yum_repository:
    name: k8s
    description: aliyun_k8s
    baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
    state: present
